version: '3.8'

services:
  # Web platform
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-cybershieldx}:${POSTGRES_PASSWORD:-cybershieldx}@db:5432/${POSTGRES_DB:-cybershieldx}
      - JWT_SECRET=${JWT_SECRET:-cybershieldxsecretchangethis}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-24h}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cybershieldx-network

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-cybershieldx}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cybershieldx}
      - POSTGRES_DB=${POSTGRES_DB:-cybershieldx}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cybershieldx-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@cybershieldx.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-cybershieldx}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cybershieldx-network

networks:
  cybershieldx-network:
    driver: bridge

volumes:
  postgres-data: